// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table TriviaTelemetry (eventId:string, eventType:string, type:string, eventName:string, userId:string, timestamp:datetime, properties:dynamic, context:dynamic, ingestedAtUtc:datetime) 
.create-or-alter table TriviaTelemetry ingestion json mapping 'TriviaTelemetryJson'
```
[{"Properties":{"Path":"$.eventId"},"column":"eventId","datatype":""},{"Properties":{"Path":"$.eventType"},"column":"eventType","datatype":""},{"Properties":{"Path":"$.type"},"column":"type","datatype":""},{"Properties":{"Path":"$.eventName"},"column":"eventName","datatype":""},{"Properties":{"Path":"$.userId"},"column":"userId","datatype":""},{"Properties":{"Path":"$.timestamp"},"column":"timestamp","datatype":""},{"Properties":{"Path":"$.properties"},"column":"properties","datatype":""},{"Properties":{"Path":"$.context"},"column":"context","datatype":""},{"Properties":{"Path":"$.ingestedAtUtc"},"column":"ingestedAtUtc","datatype":""}]
```
.create-or-alter table TriviaTelemetry ingestion json mapping 'TriviaTelemetry_mapping'
```
[{"Properties":{"Path":"$['eventId']"},"column":"eventId","datatype":""},{"Properties":{"Path":"$['eventType']"},"column":"eventType","datatype":""},{"Properties":{"Path":"$['type']"},"column":"type","datatype":""},{"Properties":{"Path":"$['eventName']"},"column":"eventName","datatype":""},{"Properties":{"Path":"$['userId']"},"column":"userId","datatype":""},{"Properties":{"Path":"$['timestamp']"},"column":"timestamp","datatype":""},{"Properties":{"Path":"$['properties']"},"column":"properties","datatype":""},{"Properties":{"Path":"$['context']"},"column":"context","datatype":""},{"Properties":{"Path":"$['ingestedAtUtc']"},"column":"ingestedAtUtc","datatype":""}]
```
.create-or-alter function with (skipvalidation = "true") TriviaEvents() { TriviaTelemetry | summarize arg_max(ingestedAtUtc, *) by eventId }
